var bob=1
console.log("AMOGUS")
console.log(bob)
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")

console.log("AMOGUS")
console.log("AMOGUS")
console.log("AMOGUS")
console.log("Among US"); 
setTimeout(() => {  console.log("World!"); }, 5000);
